# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: buildApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
   name: Test and Build
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
   - name: Build with Maven
     run: mvn -B package --file pom.xml

  deployment:
    name: Deploy to DEV ENV
    runs-on: ubuntu-latest
    needs: [test]
    steps:
     - uses: AkhileshNS/heroku-deploy@v3.12.12
     - name: copy artifacts to the Heroku
       run: mvn -B package --file pom.xml
       with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # Email that you use with heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        # The appname to use for deploying/updating
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
